app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/Movies
      password: 'Vviiggnneesshh@0'
      pool-size: 30
      username: vicky

server:
  error:
    include-binding-errors: always
    include-message: always


